java -jar compiler.jar --js ^
js/stdlib.js ^
js/libs/jquery-1.11.1.min.js ^
js/libs/underscore-min.js ^
js/libs/backbone-min.js ^
js/libs/backbone-validation-min.js ^
js/libs/Backbone.ModalDialog.js ^
js/libs/moment.min.js ^
js/libs/moment-range.js ^
js/libs/datetools.js ^
js/libs/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js ^
js/libs/timepicker/jquery.timepicker.js ^
js/libs/jquery.ui.touch-punch.min.js ^
js/libs/dragslider.js ^
js/libs/jquery.validate.min.js ^
js/libs/modernizr-2.6.2.js ^
js/libs/markerclusterer_compiled.js ^
js/libs/nanoscroller/jquery.nanoscroller.js ^
js/libs/select2/select2.js ^
js/libs/wookmark/jquery.wookmark.min.js ^
js/libs/wookmark/jquery.imagesloaded.js ^
js/libs/json3.js ^
js/app.js ^
js/collections/dawgEventCollection.js ^
js/models/dawgEventModel.js ^
js/models/dawgModel.js ^
js/models/eventMemberModel.js ^
js/models/eventModel.js ^
js/models/friendModel.js ^
js/collections/eventCollection.js ^
js/collections/eventMemberCollection.js ^
js/collections/friendCollection.js ^
js/models/facebookModel.js ^
js/models/searchModel.js ^
js/views/baseView.js ^
js/views/attendingView.js ^
js/views/eventDetailsDialogView.js ^
js/views/eventDetailsView.js ^
js/views/eventListView.js ^
js/views/editEventView.js ^
js/views/eventsView.js ^
js/views/eventView.js ^
js/views/featuredEventsView.js ^
js/views/filterView.js ^
js/views/footerView.js ^
js/views/friendsView.js ^
js/views/friendView.js ^
js/views/headerView.js ^
js/views/homeView.js ^
js/views/mapView.js ^
js/views/networkView.js ^
js/views/promoteView.js ^
js/views/publicEventsView.js ^
js/views/publicEventView.js ^
js/views/sidebarView.js ^
js/views/sliderView.js ^
js/views/topPanelView.js ^
js/views/whenView.js ^
js/views/whereView.js ^
js/router.js ^
js/main.js ^
--js_output_file dawg_compiled.js

pause